### ISSUE TITLE
how to use with prometheus-gc-stats

### ISSUE THREAD

**Issue by sakz** [willsoto/nestjs-prometheus#1650]
how to use with [prometheus-gc-stats](https://www.npmjs.com/package/prometheus-gc-stats) package

**Comment by willsoto** [comment]
I don't think anything special is required? Since `prometheus` is global, you can use this module to set it up and then in a `@Module` `onModuleInit` or something similar, you can just invoke the package as described in the docs. It seems like just invoking `const startGcStats = gcStats();` would be enough.
