### ISSUE TITLE
I can't push with pushgateway

### ISSUE THREAD

**Issue by manuelabarca** [willsoto/nestjs-prometheus#1780]
With the documentation that is in the repository it is not possible for me to understand how pushgateway works, I have the following and I have gatewayurl undefined errors.

Prom.module.ts
```typescript
import { Module } from '@nestjs/common';
import { PrometheusModule } from '@willsoto/nestjs-prometheus';
import createMetricsPlugin from 'apollo-metrics';
import { plugin as apolloTracingPlugin } from 'apollo-tracing';
import { Pushgateway, register } from 'prom-client';
import { PromService } from './prom.service';

export const TRACING_PLUGIN_KEY = 'TRACING_PLUGIN_KEY';
export const METRICS_PLUGIN_KEY = 'METRICS_PLUGIN_KEY';

@Module({
  imports: [
    PrometheusModule.register({
      pushgateway: {
        url: process.env.PUSH_GATEWAY_URL,
      },
      defaultLabels: {
        app: 'Mobile BFF',
      },
    }),
  ],
  providers: [
    PromService,
    {
      provide: TRACING_PLUGIN_KEY,
      useValue: apolloTracingPlugin(),
    },
    {
      provide: METRICS_PLUGIN_KEY,
      useValue: createMetricsPlugin(register),
    },
    Pushgateway,
  ],
  exports: [PromService, Pushgateway, TRACING_PLUGIN_KEY, METRICS_PLUGIN_KEY],
})
export class PromModule {}

``` 
PromService.ts
```typescript
import { Injectable, OnModuleInit, Logger } from '@nestjs/common';
import * as client from 'prom-client';

@Injectable()
export class PromService implements OnModuleInit {
  private readonly logger = new Logger(PromService.name);

  constructor(private readonly pushgateway: client.Pushgateway) {
    console.log('client', pushgateway);
  }

  onModuleInit() {
    this.logger.log('Pushing to prometheus gateway');
    setInterval(() => {
      this.pushgateway.push({
        jobName: 'mobile-bff',
      });
    }, 15000);
  }
}

``` 

Error in console:
```shell
TypeError: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Url.parse (node:url:169:3)
    at Object.urlParse [as parse] (node:url:156:13)
    at Pushgateway.useGateway (/Users/manuel.labarca/Desktop/mobile-bff/node_modules/prom-client/lib/pushgateway.js:46:31)
```

**Comment by willsoto** [comment]
Is `process.env.PUSH_GATEWAY_URL` defined?

**Comment by manuelabarca** [comment]
Yes 

> Is `process.env.PUSH_GATEWAY_URL` defined?

Yes is defined.

I'm assuming that when I add Pushgateway to exports and providers, the url is stepped on again and is undefined, because I've been debugging and that happens, but if I don't put that in there, I get another error.

**Comment by willsoto** [comment]
> I'm assuming that when I add Pushgateway to exports and providers, the url is stepped on again and is undefined

What do you mean by "stepped on?" Do you mean the debugger hits it?

**Comment by manuelabarca** [comment]
> What do you mean by "stepped on?" Do you mean the debugger hits it?

I mean that the url gets to gatewayurl in the library to be able to build the whole PushGateway, but when the debugger gets to the point of checking the providers and exports that url becomes undefined.

**Comment by willsoto** [comment]
There isn't much to it. The example in the docs is comprehensive. 

This is all that happens when you provide those options:

https://github.com/willsoto/nestjs-prometheus/blob/8e3802a209d30e22365e7803407a7fbe8deec493/src/module.ts#L31-L41

https://github.com/willsoto/nestjs-prometheus/blob/8e3802a209d30e22365e7803407a7fbe8deec493/src/module.ts#L137-L143

Given the error, it seems like `PUSH_GATEWAY_URL` is not defined. I would try hard coding something to see if that fixes it.

I have some [tests](https://github.com/willsoto/nestjs-prometheus/blob/main/test/push-gateway.spec.ts) but if you think there is a bug here please open a PR with the failing test case.

**Comment by willsoto** [comment]
Can you provide a complete stack trace?

**Comment by manuelabarca** [comment]
> Can you provide a complete stack trace?

When I start the application, I get those errors I told you about.

**Comment by manuelabarca** [comment]
> Neither of these things are a complete stack trace. I need to see where in the stack this library's code is being called.

I can't understand what you need to help me, when you see my code you don't see anything strange by chance? Is that pushgateway import okay? I feel like by doing that I'm creating a new instance and stomping on the previously set values.

**Comment by willsoto** [comment]
That is the only possibility I see. I will try and reproduce tonight. Otherwise, I see nothing wrong since you are just telling NestJS what _type_ to inject, not the exact instance. 

But in terms of what I need from you, a complete stack trace would be the best.

`TypeError: The "url" argument must be of type string. Received undefined`

This is just the top line of the trace and it tells me nothing about the call stack so I can't see where the library code is being hit.

**Comment by willsoto** [comment]
I've been unable to reproduce this locally. Without a proper stack trace I can't do much more. Please provide a proper stack or open a PR with a failing test case

**Comment by Terencesun** [comment]
Hi, I maybe find the reason, could I try to send a pr to this repository? @willsoto
