### ISSUE TITLE
How to add Prisma metrics

### ISSUE THREAD

**Issue by andreasciamanna** [willsoto/nestjs-prometheus#2364]
Either I need help understanding the docs or this scenario is not covered.

Prisma provides an [experimental feature for metrics](https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/metrics).

How can I merge the default `nestjs-prometheus` metrics with the Prisma ones without adding a dedicated controller for the latter?

**Comment by willsoto** [comment]
Taking a look at the docs, you are probably going to need to override the controller and merge the results of the two calls somehow. The docs seem to have that case covered.

**Comment by andreasciamanna** [comment]
I usually don't ask questions that have already been answered elsewhere.

The documentation does not cover this use case, and if it does, it's not clear where and how it explains my use case.
Sure, it mentions using custom controllers (which, to be honest, do not seem to fit my case) and custom metrics.

> merge the results of the two calls

Which calls? I know I can use `await prisma.$metrics.json()` or `prisma.$metrics.prometheus()`, but what would be the other call?
And where to use them?

The example of injecting custom metrics needs to be improved. It shows how to inject a class, and it shows that class with the `@InjectMetric("metric_name") public counter: Counter<string>` in the constructor, but it doesn't show how actually to add the metrics.


All these questions would not be necessary if the docs covered the use case.

**Comment by willsoto** [comment]
It's right here in the docs: https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/metrics#use-prisma-client-metrics-with-the-prometheus-metrics-system

<img width="1002" alt="Screenshot 2024-09-25 at 7 26 50 AM" src="https://github.com/user-attachments/assets/ec9c23e8-01bb-4afe-844c-725eaf67b9c6">

So yes, you will need to [override the controller](https://github.com/willsoto/nestjs-prometheus?tab=readme-ov-file#providing-a-custom-controller) in order to merge the results of the two calls to be available on the single endpoint being scraped.
