### ISSUE TITLE
Using the latest version of NestJS and Fastify Adapter, I cannot initiate Prometheus

### ISSUE THREAD

**Issue by lehno** [willsoto/nestjs-prometheus#530]
Even using a custom controller, this error happens
![image](https://user-images.githubusercontent.com/5764569/96869945-18ca5680-1468-11eb-864a-730c373d8f4e.png)

**Comment by willsoto** [comment]
@lehno can you `npm i @types/express --save-dev`?

**Comment by lehno** [comment]
Do I need to use @types/express even when using Fastify?

**Comment by willsoto** [comment]
Because I wrote the controller using `express`'s response, they would be needed yeah. I can probably rewrite it so it doesn't require one vs the other.

Do you happen to have `skipLibCheck` enabled in your `tsconfig`?

**Comment by lehno** [comment]
I don't have skipLibCheck enabled. Using all default values from NestJS and changed Express to Fastify for performance.
Tks for the explanation

**Comment by willsoto** [comment]
As a workaround, I would suggest enabling `skipLibCheck` since I believe it makes it so your application won't have an issue if there are typings issues in other people's libraries (like this case). 

I have marked this as a bug though since I don't think it's reasonable for people to have to install typings for express if they aren't using it OR have to tweak their tsconfig settings to use this library.

I'll try and get a fix out in the next few days.

**Comment by lehno** [comment]
That is great, thanks again

**Comment by willsoto** [comment]
@lehno Sorry for the delay. Released as v2.0.1. Please let me know if it works.

**Comment by lehno** [comment]
I will test soon
